name: Publish Docker image

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions-ecosystem/action-regex-match@v2
        id: regex_mainline
        with:
          text: ${{ github.ref }}
          regex: '^refs/tags/\d+.\d*[13579].\d+'

      - uses: actions-ecosystem/action-regex-match@v2
        id: regex_stable
        with:
          text: ${{ github.ref }}
          regex: '^refs/tags/\d+.\d*[02468].\d+'

      - name: Select version
        uses: actions/github-script@v4
        id: version
        with:
          script: |
            console.log(context.ref)
            if (/^refs\/tags\/\d+.\d*[02468].\d+/.test(context.ref)) {
              console.log('stable')
              return 'stable'
            } else {
              console.log('mainline')
              return 'mainline'
            }

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            yano3/nginx-sandbox
            ghcr.io/yano3/nginx-sandbox
          tags: |
            type=ref,event=tag
            type=raw,value=latest,enable=${{ steps.regex_mainline.outputs.match != '' }}
            type=raw,value=stable,enable=${{ steps.regex_stable.outputs.match != '' }}
          flavor: |
            latest=false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_ID }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./${{ steps.version.outputs.result }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_HUB_ID }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: yano3/nginx-sandbox
