name: Publish Docker image

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Detect nginx version
        uses: actions/github-script@v6
        id: version
        with:
          result-encoding: string
          script: |
            if (/^refs\/tags\/\d+.\d*[02468].\d+/.test(context.ref)) {
              return 'stable'
            } else {
              return 'mainline'
            }

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            yano3/nginx-sandbox
            ghcr.io/yano3/nginx-sandbox
          tags: |
            type=ref,event=tag
            type=raw,value=${{ steps.version.outputs.result }}
          flavor: |
            latest=${{ steps.version.outputs.result == 'mainline' }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_ID }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./${{ steps.version.outputs.result }}/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_HUB_ID }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: yano3/nginx-sandbox
